# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fbfc56bf3e0552b8da6e078e97dd8d5f45b4e315c0a9c2e98e54a5377ce835b5e4ae801dcb44ed7c63a59d1769ed9842193c7ec4c97407c9b0d5074f38c6a7d

test:
  secret_key_base: 11cc2e08b8ca59c1b83f697d9f5618a96eb06de9edbe37d7eab5fdd53e282bba384633fc4e74073f9c5c25bae3d835bacc7667a97c1d42bea78bfb0edf19b7bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
